//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.0
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUI {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegisterNotes.WebUI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация пользователя.
        /// </summary>
        public static string BtnRegNewUser {
            get {
                return ResourceManager.GetString("BtnRegNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр логов.
        /// </summary>
        public static string MenuLogFile {
            get {
                return ResourceManager.GetString("MenuLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление пользователями, через администратора.
        /// </summary>
        public static string MenuManage {
            get {
                return ResourceManager.GetString("MenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список записей.
        /// </summary>
        public static string MenuNoteList {
            get {
                return ResourceManager.GetString("MenuNoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string MenuRegistration {
            get {
                return ResourceManager.GetString("MenuRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный адрес электронной почты.
        /// </summary>
        public static string ModelEmailWrong {
            get {
                return ResourceManager.GetString("ModelEmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string ModelPasswordDisplay {
            get {
                return ResourceManager.GetString("ModelPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется указать пароль.
        /// </summary>
        public static string ModelPasswordRequired {
            get {
                return ResourceManager.GetString("ModelPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не соответствует уровню сложности.
        /// </summary>
        public static string ModelPasswordWrong {
            get {
                return ResourceManager.GetString("ModelPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string ModelRememberMeDisplay {
            get {
                return ResourceManager.GetString("ModelRememberMeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string ModelUserNameDisplay {
            get {
                return ResourceManager.GetString("ModelUserNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется указать имя пользователя.
        /// </summary>
        public static string ModelUserNameRequired {
            get {
                return ResourceManager.GetString("ModelUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В качестве имени входа используется адрес электронной почты..
        /// </summary>
        public static string MsgLine1 {
            get {
                return ResourceManager.GetString("MsgLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это сделано с целью сделать вход в систему более удобным..
        /// </summary>
        public static string MsgLine2 {
            get {
                return ResourceManager.GetString("MsgLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для простоты запоминания и получения возможности восстановления пароля..
        /// </summary>
        public static string MsgLine3 {
            get {
                return ResourceManager.GetString("MsgLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить сообщение.
        /// </summary>
        public static string NavAddNote {
            get {
                return ResourceManager.GetString("NavAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категории сообщений.
        /// </summary>
        public static string NavCategories {
            get {
                return ResourceManager.GetString("NavCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неопределенные.
        /// </summary>
        public static string NavDnDef {
            get {
                return ResourceManager.GetString("NavDnDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все сообщения.
        /// </summary>
        public static string NavFullList {
            get {
                return ResourceManager.GetString("NavFullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личные.
        /// </summary>
        public static string NavPrivate {
            get {
                return ResourceManager.GetString("NavPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Публичные.
        /// </summary>
        public static string NavPublic {
            get {
                return ResourceManager.GetString("NavPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string PhlEmailAddress {
            get {
                return ResourceManager.GetString("PhlEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PhlPassword {
            get {
                return ResourceManager.GetString("PhlPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по ключевому слову.
        /// </summary>
        public static string PhlSearch {
            get {
                return ResourceManager.GetString("PhlSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для регистрации свяжитесь с администратором.
        /// </summary>
        public static string PpvCallAdmin {
            get {
                return ResourceManager.GetString("PpvCallAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служба регистрации.
        /// </summary>
        public static string PpvRegService {
            get {
                return ResourceManager.GetString("PpvRegService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С уважением, администрация.
        /// </summary>
        public static string TtlAdminSign {
            get {
                return ResourceManager.GetString("TtlAdminSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация cообщений.
        /// </summary>
        public static string TtlBrandName {
            get {
                return ResourceManager.GetString("TtlBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лист сообщений.
        /// </summary>
        public static string TtlListNotes {
            get {
                return ResourceManager.GetString("TtlListNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение входа.
        /// </summary>
        public static string TtlLogin {
            get {
                return ResourceManager.GetString("TtlLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход с локальной учетной записью.
        /// </summary>
        public static string TtlLoginLocal {
            get {
                return ResourceManager.GetString("TtlLoginLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение для пользователей.
        /// </summary>
        public static string TtlMessageForUsers {
            get {
                return ResourceManager.GetString("TtlMessageForUsers", resourceCulture);
            }
        }
    }
}
